version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - echo "Installing dependencies..."
      - npm install
  build:
    commands:
      - echo "Building React app..."
      - npm run build
  post_build:
    commands:
      - echo "Uploading build artifacts to S3..."
      - aws s3 sync build/ s3://dynamic-website-devops --delete
artifacts:
  files:
    - '**/*'
  base-directory: build
